trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: rest-assured-framework-variables

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo $(baseUrl)
        echo $(refreshToken)
        export refreshToken="$(refreshToken)"
        export baseUrl="$(baseUrl)"
        echo $baseUrl
        echo $refreshToken
  
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'
