trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: rest-assured-framework-variables

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo "Base URL: $baseUrl"
        echo "Refresh Token: $refreshToken"
        export baseUrl="$baseUrl"
        export refreshToken="$refreshToken"
        echo "Exported Base URL: $baseUrl"
        echo "Exported Refresh Token: $refreshToken"
  
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'
